/*
   -- New project --
   
   To compile this code using RemoteXY library 4.1.8 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.18.03 or later version;
     - for iOS 1.14.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__WIFI_POINT

#include <ESP8266WiFi.h>

// RemoteXY connection settings 
#define REMOTEXY_WIFI_SSID "Maker_Car1"
#define REMOTEXY_WIFI_PASSWORD ""
#define REMOTEXY_SERVER_PORT 6377


#include <RemoteXY.h>

uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =   // 65 bytes V19 
  { 255,3,0,0,0,58,0,19,0,0,0,77,97,107,101,114,32,67,97,114,
  0,31,2,106,200,200,84,1,1,2,0,5,24,63,60,60,69,10,63,63,
  47,2,26,31,2,4,22,23,52,12,7,35,20,0,2,26,31,31,79,78,
  0,79,70,70,0 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // input variables
  int8_t joystick_01_x; // from -100 to 100
  int8_t joystick_01_y; // from -100 to 100
  uint8_t switch_01; // =1 if switch ON and =0 if OFF, from 0 to 1

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
 
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////

// Motor Driver Pins
#define MOTOR_DRIVER_OUT_1 13 // D7
#define MOTOR_DRIVER_OUT_2 15 // D8
#define MOTOR_DRIVER_OUT_3 0  // D3
#define MOTOR_DRIVER_OUT_4 2  // D4

int right_motor[2] = {MOTOR_DRIVER_OUT_1, MOTOR_DRIVER_OUT_2};
int left_motor[2]  = {MOTOR_DRIVER_OUT_3, MOTOR_DRIVER_OUT_4};





void setup() 
{
  // Begin serial communnications
  Serial.begin(115200);

  // Set the pins to OUTPUT
  pinMode(MOTOR_DRIVER_OUT_1, OUTPUT);
  pinMode(MOTOR_DRIVER_OUT_2, OUTPUT);
  pinMode(MOTOR_DRIVER_OUT_3, OUTPUT);
  pinMode(MOTOR_DRIVER_OUT_4, OUTPUT);

  // Make sure the motors are off
  digitalWrite(MOTOR_DRIVER_OUT_1, LOW);
  digitalWrite(MOTOR_DRIVER_OUT_2, LOW);
  digitalWrite(MOTOR_DRIVER_OUT_3, LOW);
  digitalWrite(MOTOR_DRIVER_OUT_4, LOW);
  
  RemoteXY_Init ();  // initialization by macros 
}

void loop() 
{ 
  RemoteXYEngine.handler ();   
  
  // Show the variables
  Serial.print("joystick-01 [");
  Serial.print(RemoteXY.joystick_01_x);
  Serial.print(", ");
  Serial.print(RemoteXY.joystick_01_y);
  Serial.print("]");
  Serial.println();

  drive(left_motor, RemoteXY.joystick_01_y - RemoteXY.joystick_01_x);
  drive(right_motor, RemoteXY.joystick_01_y + RemoteXY.joystick_01_x);

  // TODO you loop code
  // use the RemoteXY structure for data transfer
  // do not call delay(), use instead RemoteXYEngine.delay() 

}

void drive(int motor[], int v)
{
  if (v>100) v=100;
  if (v<-100) v=-100;
  if (v>0) 
  {
    digitalWrite(motor[0], HIGH);
    analogWrite(motor[1], 255-(v*2.55));
  }
    else if (v<0) {
    digitalWrite(motor[1], HIGH);
    analogWrite(motor[0], 255+((v)*2.55));
  }
  else {
    digitalWrite(motor[0], LOW);
    digitalWrite(motor[1], LOW);
  }
  Serial.println(v);
}

